### ISSUE TITLE
DIR Change for Step 7. under Compile Ardupilot

### ISSUE THREAD

**Issue by aircool00** [mirkix/ardupilotblue#1]
I found that step 7 needs to be modified. The Ardupilot uses different directory name now for Beagle Bone Blue builds in current master repo. 
7.`cp build/bbbmini/bin/* /home/debian/`
Should be changed to
7.`cp build/blue/bin/* /home/debian/`

**Comment by mirkix** [comment]
@aircool00 Thanks, fixed.
