### ISSUE TITLE
E4 Pin 4

### ISSUE THREAD

**Issue by ccsmart** [mirkix/ardupilotblue#10]
"The RC receiver signal has to be connected to connector E4 pin 4."
No documentation I was able to find can resolve "E4 pin 4".

**Comment by juvinski** [comment]
hi @ccsmart ,
What problem are you having ?
What is happening or not ?

**Comment by ccsmart** [comment]
Just literally. Which connector on BBB do you reference as "E4" ? The PCB appears to have none labelled this way and in documentation i didnt find that reference. The only connector that by itself has a design reference to RC would be DSM, but that has 3 pins only.
So i'm lost.
