### ISSUE TITLE
ardurover 

### ISSUE THREAD

**Issue by MONICA-PALLA** [mirkix/ardupilotblue#7]
In the link mentioned below, I could find the executable codes only for Arducopter and Arduplane
http://bbbmini.org/download/blue/

may I where I can find the Ardurover executable file?

Thank you,
Monica, P.

**Comment by mirkix** [comment]
@MONICA-PALLA  Please check http://bbbmini.org/download/blue/ArduRover/ is it is working.

**Comment by MONICA-PALLA** [comment]
Thank you very much.
